// Generated by CoffeeScript 1.7.1
var fn,
  __slice = [].slice;

fn = {};

fn.iffn = function() {
  var f, rest;
  f = arguments[0], rest = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
  if (fn.isfn(f)) {
    return f.apply(rest);
  } else {
    return null;
  }
};

fn.isfn = function(f) {
  return typeof f === 'function';
};

fn.trapError = function(err) {
  console.log("Unhandled exception: " + err);
  if (err.stack) {
    return console.log(err.stack);
  }
};

fn.tryRequire = function(fp, errval, log) {
  var err;
  try {
    return require(fp);
  } catch (_error) {
    err = _error;
    if (log) {
      console.err("Could not require " + fp);
    }
    return errval;
  }
};

module.exports = fn;
